/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BadgesRouteImport } from './routes/badges'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as ChainOfKindnessRouteImport } from './routes/chain-of-kindness'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as MyOpportunitiesRouteImport } from './routes/my-opportunities'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VolunteerIdRouteImport } from './routes/volunteer-id'
import { Route as LoginIndexRouteImport } from './routes/login.index'
import { Route as LoginOrganizationRouteImport } from './routes/login.organization'
import { Route as LoginVolunteerRouteImport } from './routes/login.volunteer'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as OnboardingAiRouteImport } from './routes/onboarding.ai'
import { Route as OnboardingGameRouteImport } from './routes/onboarding.game'
import { Route as OpportunitiesIdRouteImport } from './routes/opportunities.$id'
import { Route as OrganizationIndexRouteImport } from './routes/organization.index'
import { Route as OrganizationCertificatesRouteImport } from './routes/organization.certificates'
import { Route as OrganizationDirectoryRouteImport } from './routes/organization.directory'
import { Route as OrganizationOpportunitiesRouteImport } from './routes/organization.opportunities'
import { Route as OrganizationPaymentsRouteImport } from './routes/organization.payments'
import { Route as OrganizationRatingsRouteImport } from './routes/organization.ratings'
import { Route as OrganizationSettingsRouteImport } from './routes/organization.settings'
import { Route as OrganizationVolunteersRouteImport } from './routes/organization.volunteers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgesRoute = BadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const ChainOfKindnessRoute = ChainOfKindnessRouteImport.update({
  id: '/chain-of-kindness',
  path: '/chain-of-kindness',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const MyOpportunitiesRoute = MyOpportunitiesRouteImport.update({
  id: '/my-opportunities',
  path: '/my-opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerIdRoute = VolunteerIdRouteImport.update({
  id: '/volunteer-id',
  path: '/volunteer-id',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginOrganizationRoute = LoginOrganizationRouteImport.update({
  id: '/login/organization',
  path: '/login/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginVolunteerRoute = LoginVolunteerRouteImport.update({
  id: '/login/volunteer',
  path: '/login/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingAiRoute = OnboardingAiRouteImport.update({
  id: '/onboarding/ai',
  path: '/onboarding/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingGameRoute = OnboardingGameRouteImport.update({
  id: '/onboarding/game',
  path: '/onboarding/game',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIdRoute = OpportunitiesIdRouteImport.update({
  id: '/opportunities/$id',
  path: '/opportunities/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationIndexRoute = OrganizationIndexRouteImport.update({
  id: '/organization/',
  path: '/organization/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationCertificatesRoute =
  OrganizationCertificatesRouteImport.update({
    id: '/organization/certificates',
    path: '/organization/certificates',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizationDirectoryRoute = OrganizationDirectoryRouteImport.update({
  id: '/organization/directory',
  path: '/organization/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationOpportunitiesRoute =
  OrganizationOpportunitiesRouteImport.update({
    id: '/organization/opportunities',
    path: '/organization/opportunities',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizationPaymentsRoute = OrganizationPaymentsRouteImport.update({
  id: '/organization/payments',
  path: '/organization/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRatingsRoute = OrganizationRatingsRouteImport.update({
  id: '/organization/ratings',
  path: '/organization/ratings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationSettingsRoute = OrganizationSettingsRouteImport.update({
  id: '/organization/settings',
  path: '/organization/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationVolunteersRoute = OrganizationVolunteersRouteImport.update({
  id: '/organization/volunteers',
  path: '/organization/volunteers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/badges': typeof BadgesRoute
  '/browse': typeof BrowseRoute
  '/certificates': typeof CertificatesRoute
  '/chain-of-kindness': typeof ChainOfKindnessRoute
  '/discover': typeof DiscoverRoute
  '/help': typeof HelpRoute
  '/impact': typeof ImpactRoute
  '/my-opportunities': typeof MyOpportunitiesRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/volunteer-id': typeof VolunteerIdRoute
  '/login/organization': typeof LoginOrganizationRoute
  '/login/volunteer': typeof LoginVolunteerRoute
  '/onboarding/ai': typeof OnboardingAiRoute
  '/onboarding/game': typeof OnboardingGameRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/organization/certificates': typeof OrganizationCertificatesRoute
  '/organization/directory': typeof OrganizationDirectoryRoute
  '/organization/opportunities': typeof OrganizationOpportunitiesRoute
  '/organization/payments': typeof OrganizationPaymentsRoute
  '/organization/ratings': typeof OrganizationRatingsRoute
  '/organization/settings': typeof OrganizationSettingsRoute
  '/organization/volunteers': typeof OrganizationVolunteersRoute
  '/login/': typeof LoginIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/organization/': typeof OrganizationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/badges': typeof BadgesRoute
  '/browse': typeof BrowseRoute
  '/certificates': typeof CertificatesRoute
  '/chain-of-kindness': typeof ChainOfKindnessRoute
  '/discover': typeof DiscoverRoute
  '/help': typeof HelpRoute
  '/impact': typeof ImpactRoute
  '/my-opportunities': typeof MyOpportunitiesRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/volunteer-id': typeof VolunteerIdRoute
  '/login/organization': typeof LoginOrganizationRoute
  '/login/volunteer': typeof LoginVolunteerRoute
  '/onboarding/ai': typeof OnboardingAiRoute
  '/onboarding/game': typeof OnboardingGameRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/organization/certificates': typeof OrganizationCertificatesRoute
  '/organization/directory': typeof OrganizationDirectoryRoute
  '/organization/opportunities': typeof OrganizationOpportunitiesRoute
  '/organization/payments': typeof OrganizationPaymentsRoute
  '/organization/ratings': typeof OrganizationRatingsRoute
  '/organization/settings': typeof OrganizationSettingsRoute
  '/organization/volunteers': typeof OrganizationVolunteersRoute
  '/login': typeof LoginIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/organization': typeof OrganizationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/badges': typeof BadgesRoute
  '/browse': typeof BrowseRoute
  '/certificates': typeof CertificatesRoute
  '/chain-of-kindness': typeof ChainOfKindnessRoute
  '/discover': typeof DiscoverRoute
  '/help': typeof HelpRoute
  '/impact': typeof ImpactRoute
  '/my-opportunities': typeof MyOpportunitiesRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/volunteer-id': typeof VolunteerIdRoute
  '/login/organization': typeof LoginOrganizationRoute
  '/login/volunteer': typeof LoginVolunteerRoute
  '/onboarding/ai': typeof OnboardingAiRoute
  '/onboarding/game': typeof OnboardingGameRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/organization/certificates': typeof OrganizationCertificatesRoute
  '/organization/directory': typeof OrganizationDirectoryRoute
  '/organization/opportunities': typeof OrganizationOpportunitiesRoute
  '/organization/payments': typeof OrganizationPaymentsRoute
  '/organization/ratings': typeof OrganizationRatingsRoute
  '/organization/settings': typeof OrganizationSettingsRoute
  '/organization/volunteers': typeof OrganizationVolunteersRoute
  '/login/': typeof LoginIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/organization/': typeof OrganizationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/badges'
    | '/browse'
    | '/certificates'
    | '/chain-of-kindness'
    | '/discover'
    | '/help'
    | '/impact'
    | '/my-opportunities'
    | '/notifications'
    | '/payments'
    | '/settings'
    | '/signup'
    | '/volunteer-id'
    | '/login/organization'
    | '/login/volunteer'
    | '/onboarding/ai'
    | '/onboarding/game'
    | '/opportunities/$id'
    | '/organization/certificates'
    | '/organization/directory'
    | '/organization/opportunities'
    | '/organization/payments'
    | '/organization/ratings'
    | '/organization/settings'
    | '/organization/volunteers'
    | '/login/'
    | '/onboarding/'
    | '/organization/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/badges'
    | '/browse'
    | '/certificates'
    | '/chain-of-kindness'
    | '/discover'
    | '/help'
    | '/impact'
    | '/my-opportunities'
    | '/notifications'
    | '/payments'
    | '/settings'
    | '/signup'
    | '/volunteer-id'
    | '/login/organization'
    | '/login/volunteer'
    | '/onboarding/ai'
    | '/onboarding/game'
    | '/opportunities/$id'
    | '/organization/certificates'
    | '/organization/directory'
    | '/organization/opportunities'
    | '/organization/payments'
    | '/organization/ratings'
    | '/organization/settings'
    | '/organization/volunteers'
    | '/login'
    | '/onboarding'
    | '/organization'
  id:
    | '__root__'
    | '/'
    | '/badges'
    | '/browse'
    | '/certificates'
    | '/chain-of-kindness'
    | '/discover'
    | '/help'
    | '/impact'
    | '/my-opportunities'
    | '/notifications'
    | '/payments'
    | '/settings'
    | '/signup'
    | '/volunteer-id'
    | '/login/organization'
    | '/login/volunteer'
    | '/onboarding/ai'
    | '/onboarding/game'
    | '/opportunities/$id'
    | '/organization/certificates'
    | '/organization/directory'
    | '/organization/opportunities'
    | '/organization/payments'
    | '/organization/ratings'
    | '/organization/settings'
    | '/organization/volunteers'
    | '/login/'
    | '/onboarding/'
    | '/organization/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BadgesRoute: typeof BadgesRoute
  BrowseRoute: typeof BrowseRoute
  CertificatesRoute: typeof CertificatesRoute
  ChainOfKindnessRoute: typeof ChainOfKindnessRoute
  DiscoverRoute: typeof DiscoverRoute
  HelpRoute: typeof HelpRoute
  ImpactRoute: typeof ImpactRoute
  MyOpportunitiesRoute: typeof MyOpportunitiesRoute
  NotificationsRoute: typeof NotificationsRoute
  PaymentsRoute: typeof PaymentsRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  VolunteerIdRoute: typeof VolunteerIdRoute
  LoginOrganizationRoute: typeof LoginOrganizationRoute
  LoginVolunteerRoute: typeof LoginVolunteerRoute
  OnboardingAiRoute: typeof OnboardingAiRoute
  OnboardingGameRoute: typeof OnboardingGameRoute
  OpportunitiesIdRoute: typeof OpportunitiesIdRoute
  OrganizationCertificatesRoute: typeof OrganizationCertificatesRoute
  OrganizationDirectoryRoute: typeof OrganizationDirectoryRoute
  OrganizationOpportunitiesRoute: typeof OrganizationOpportunitiesRoute
  OrganizationPaymentsRoute: typeof OrganizationPaymentsRoute
  OrganizationRatingsRoute: typeof OrganizationRatingsRoute
  OrganizationSettingsRoute: typeof OrganizationSettingsRoute
  OrganizationVolunteersRoute: typeof OrganizationVolunteersRoute
  LoginIndexRoute: typeof LoginIndexRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  OrganizationIndexRoute: typeof OrganizationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badges': {
      id: '/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof BadgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chain-of-kindness': {
      id: '/chain-of-kindness'
      path: '/chain-of-kindness'
      fullPath: '/chain-of-kindness'
      preLoaderRoute: typeof ChainOfKindnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-opportunities': {
      id: '/my-opportunities'
      path: '/my-opportunities'
      fullPath: '/my-opportunities'
      preLoaderRoute: typeof MyOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer-id': {
      id: '/volunteer-id'
      path: '/volunteer-id'
      fullPath: '/volunteer-id'
      preLoaderRoute: typeof VolunteerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/organization': {
      id: '/login/organization'
      path: '/login/organization'
      fullPath: '/login/organization'
      preLoaderRoute: typeof LoginOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/volunteer': {
      id: '/login/volunteer'
      path: '/login/volunteer'
      fullPath: '/login/volunteer'
      preLoaderRoute: typeof LoginVolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/ai': {
      id: '/onboarding/ai'
      path: '/onboarding/ai'
      fullPath: '/onboarding/ai'
      preLoaderRoute: typeof OnboardingAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/game': {
      id: '/onboarding/game'
      path: '/onboarding/game'
      fullPath: '/onboarding/game'
      preLoaderRoute: typeof OnboardingGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$id': {
      id: '/opportunities/$id'
      path: '/opportunities/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof OpportunitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/': {
      id: '/organization/'
      path: '/organization'
      fullPath: '/organization/'
      preLoaderRoute: typeof OrganizationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/certificates': {
      id: '/organization/certificates'
      path: '/organization/certificates'
      fullPath: '/organization/certificates'
      preLoaderRoute: typeof OrganizationCertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/directory': {
      id: '/organization/directory'
      path: '/organization/directory'
      fullPath: '/organization/directory'
      preLoaderRoute: typeof OrganizationDirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/opportunities': {
      id: '/organization/opportunities'
      path: '/organization/opportunities'
      fullPath: '/organization/opportunities'
      preLoaderRoute: typeof OrganizationOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/payments': {
      id: '/organization/payments'
      path: '/organization/payments'
      fullPath: '/organization/payments'
      preLoaderRoute: typeof OrganizationPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/ratings': {
      id: '/organization/ratings'
      path: '/organization/ratings'
      fullPath: '/organization/ratings'
      preLoaderRoute: typeof OrganizationRatingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/settings': {
      id: '/organization/settings'
      path: '/organization/settings'
      fullPath: '/organization/settings'
      preLoaderRoute: typeof OrganizationSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/volunteers': {
      id: '/organization/volunteers'
      path: '/organization/volunteers'
      fullPath: '/organization/volunteers'
      preLoaderRoute: typeof OrganizationVolunteersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BadgesRoute: BadgesRoute,
  BrowseRoute: BrowseRoute,
  CertificatesRoute: CertificatesRoute,
  ChainOfKindnessRoute: ChainOfKindnessRoute,
  DiscoverRoute: DiscoverRoute,
  HelpRoute: HelpRoute,
  ImpactRoute: ImpactRoute,
  MyOpportunitiesRoute: MyOpportunitiesRoute,
  NotificationsRoute: NotificationsRoute,
  PaymentsRoute: PaymentsRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  VolunteerIdRoute: VolunteerIdRoute,
  LoginOrganizationRoute: LoginOrganizationRoute,
  LoginVolunteerRoute: LoginVolunteerRoute,
  OnboardingAiRoute: OnboardingAiRoute,
  OnboardingGameRoute: OnboardingGameRoute,
  OpportunitiesIdRoute: OpportunitiesIdRoute,
  OrganizationCertificatesRoute: OrganizationCertificatesRoute,
  OrganizationDirectoryRoute: OrganizationDirectoryRoute,
  OrganizationOpportunitiesRoute: OrganizationOpportunitiesRoute,
  OrganizationPaymentsRoute: OrganizationPaymentsRoute,
  OrganizationRatingsRoute: OrganizationRatingsRoute,
  OrganizationSettingsRoute: OrganizationSettingsRoute,
  OrganizationVolunteersRoute: OrganizationVolunteersRoute,
  LoginIndexRoute: LoginIndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  OrganizationIndexRoute: OrganizationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
